apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-flask-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-flask-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
